
export const USER_SIGN_UP_STATUS = "USER_SIGN_UP_STATUS"
export const USER_SIGN_UP_RESPONSE = "USER_SIGN_UP_RESPONSE"
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR"

//action types for the login user
export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

//action types for the register room
export const ROOM_REGISTER_STATUS = "ROOM_REGISTER_STATUS"
export const ROOM_REGISTER_RESPONSE = "ROOM_REGISTER_RESPONSE"
export const ROOM_REGISTER_ERROR = "ROOM_REGISTER_ERROR"
//room image upload
export const ROOM_IMG_UPLOAD_STATUS = "ROOM_IMG_UPLOAD_STATUS"
export const ROOM_IMG_UPLOAD_RESPONSE = "ROOM_IMG_UPLOAD_RESPONSE"
export const ROOM_IMG_UPLOAD_ERROR = "ROOM_IMG_UPLOAD_ERROR"
